name: Profile README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - uses: actions/setup-python@main
      # https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
        with:
          python-version: 3.12
      - name: Create Chart
        run: pip install -r requirements.txt
      - env:
          USERNAME: ${{ secrets.USERNAME }}
          TIME_CLASS: blitz
          RULES: chess
          NGAMES: 100
        run: |-
          sh -c 'chmod +x rating_chart.py'
          python rating_chart.py > assets/images/chart.txt
          CHART=$(cat assets/images/chart.txt)
          echo "::set-output name=chart::$CHART"
      - name: Use Go1.23
        uses: actions/setup-go@main
        with:
          go-version: '>=1.23.0'
      - name: Install Dependencies
        run: |-
          go mod tidy
      - name: Rebuild README.md File
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |-
          rm -f README.md assets/images/*.svg
          go run main.go
          cat assets/README-1.md >> README.md
          cat assets/images/chart.txt >> README.md
          currentDate=`env TZ=America/New_York date`
          printf "\nChart last updated - ${currentDate}" >> README.md
          cat assets/README-2.md >> README.md
      - name: Commit and Push if Changed
        run: |-
          git diff
          git add .
          git config --global user.email "shashank9163882019@gmail.com"
          git config --global user.name "BA Actions Bot"
          git commit -m "docs: auto-update README.md" -a || exit 0
          git pull 
          git push