name: Profile README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Use Go1.21
        uses: actions/setup-go@v4
        with:
            go-version: '1.21'  
      - name: Install Dependencies
        run: |-
          go mod tidy
          rm README.md ./assets/images/stats.svg
      - name: Rebuild README.md File
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go run main.go
      - name: Commit and Push if Changed
        run: |-
          git add .
          git diff
          git config --global user.email "shashank9163882019@gmail.com"
          git config --global user.name "BA Actions Bot"
          git commit -m "docs: auto-update README.md" -a || exit 0
          git push